### ISSUE TITLE
i need tutorial video or pdf document step by step for apex tooltip please help me in this regards.

### ISSUE THREAD

**Issue by muqbilkhan** [Dani3lSun/apex-plugin-apextooltip#1]

**Comment by Dani3lSun** [comment]
Hi @muqbilkhan 
for better understanding how to implement the plugin, I have created a simple one page example app with the most common plugin settings...Just download it and import to your APEX workspace.
Hope that helps!;)
[f611_tooltip_example.zip](https://github.com/Dani3lSun/apex-plugin-apextooltip/files/216642/f611_tooltip_example.zip)

**Comment by muqbilkhan** [comment]
i need select2 plugin and combo box plugin for apex 5. please help me in this regards.

**Comment by Dani3lSun** [comment]
For this I would suggest you to open a issue on select2 creators repo:
https://github.com/nbuytaert1/apex-select2
