### ISSUE TITLE
Steps after dynamic action

### ISSUE THREAD

**Issue by timurcatakli** [Dani3lSun/apex-plugin-apextooltip#2]
Hello there,

I loved your plugin. I imported the sql file
Created a dynamic action but I have no idea how to have add tooltip to a column.

Can you also double check my dynamic action settings.

Thanks,
![screen shot 2016-07-01 at 11 29 46 am](https://cloud.githubusercontent.com/assets/15508978/16530876/ef31c9f6-3f7e-11e6-9204-1334eaa393e2.png)

**Comment by Dani3lSun** [comment]
Hi @timurcatakli 
thanks for the flowers!:)
I created a simple demo app that shows the most common settings (includes adding a tooltip to a report column).
Simply said you have to do these steps:
- add a class to your report column, e.g. "my_tooltip_col"
- add the tooltip plugin to your page and under affected elements choose jquery selector with ".my_tooltip_col" from before

Hope this helps!;)
[tooltip_demo_app.zip](https://github.com/Dani3lSun/apex-plugin-apextooltip/files/344550/tooltip_demo_app.zip)

**Comment by timurcatakli** [comment]
Thanks will take a loo at it :-)
