### ISSUE TITLE
Toolpit in an IR to show content of a (hidden) cell

### ISSUE THREAD

**Issue by pettinger** [Dani3lSun/apex-plugin-apextooltip#3]
How can i use the plugin in an IR to show the content of a hidden cell as tooltip of another cell of the same row? I can't use the usual #rowname# format to adress the content.

thanks in advance
peter

**Comment by Dani3lSun** [comment]
Hi @pettinger 

I just released a new version of this plugin to handle this kind of requirement...
You can find it here:
https://github.com/Dani3lSun/apex-plugin-apextooltip/releases/tag/v1.1

Short description how to handle it:

**In your report**
HTML Expression of visible column:

```
<span class="ir_tooltip" title="#TEXT_HIDDEN_COLUMN#">#DISPLAY_COLUMN#</span>
```

**In the Plugin settings**
- Content text source: Text from title attribute
- Affected Elements: JQuery Selector --> .ir_tooltip

Hope it works out well for you!;)

**Comment by pettinger** [comment]
Hi,
you are awesome. Works great, U made my day.

Thx
Peter

**Comment by Dani3lSun** [comment]
Ok I found the class that creates the problem...If the maximize button is pressed a class called "js-regionIsMaximized" is added to the body, in css in looks like this:

```
.js-regionIsMaximized {
    visibility: hidden;
}
```
The hidden visibility also hides the tooltip...
