### ISSUE TITLE
Plugin does not work after "maximize" the IR

### ISSUE THREAD

**Issue by pettinger** [Dani3lSun/apex-plugin-apextooltip#4]
### Expected behavior

Tooltips should show up, no matter which view option user chooses
### Actual behavior

After maximizing the IR tooltips are not shown any longer
### Steps to reproduce the issue

Create an IR whith the "Maximiz" Button enabled. 
Start IR. Hovering over the designated column shows tooltip.
Use the Maximize Button. Tooltips will not show up.
Switch back to "normal" view. Tooltips show up again
### APEX version (4.2.6 / 5.0.3)

5.0.3
### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

ORDS
### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)

Windows FF

**Comment by Dani3lSun** [comment]
Hi @pettinger 

can you please try to add the Tooltip DA not on page load instead use event "After Refresh" with your IR region as affected element.
You can also try to alter the event scope from "static" to "dynamic"...

**Comment by pettinger** [comment]
@Dani3lSun Thats exactly how i configured the da. otherwise it would not work after pagination 
![2016-08-19 10_48_18-tooltipregion](https://cloud.githubusercontent.com/assets/20111123/17804264/0278cc2e-65fb-11e6-9108-ce1862fdfa65.jpg)

**Comment by Dani3lSun** [comment]
OK, I will try to reproduce your issue and come back to you!
Hope I can make it until the end of this weekend!;)

**Comment by Dani3lSun** [comment]
Ok I found the class that creates the problem...If the maximize button is pressed a class called "js-regionIsMaximized" is added to the body, in css in looks like this:

```
.js-regionIsMaximized {
    visibility: hidden;
}
```

The hidden visibility also hides the tooltip...

**Comment by Dani3lSun** [comment]
@pettinger I found some workaround to get it working, not the best solution but it works...
- Give your IR region a static ID
- add this JS snipped on page load DA:

```
$('.t-Button--noUI[aria-controls="YOUR_STATIC_ID"]').click(function(){
  $('#t_PageBody').removeClass('js-regionIsMaximized');
  if ( $('#wwvFlowForm').hasClass('js-regionIsMaximized')) {
    $('#wwvFlowForm').removeClass('js-regionIsMaximized');
  } else {
    $('#wwvFlowForm').addClass('js-regionIsMaximized');
  }
});
```

This removes the problematic class "js-regionIsMaximized" from the body and adds it to the wwvflow form. This have to be done because only removing it from body shows the menubar of the app, back adding it to the form hides the menubar again...

I will search for an nicer solution but it works for now.

**Comment by Dani3lSun** [comment]
This would be nicer, because it works for all regions with maximize button:

```
$('.js-maximizeButtonContainer').click(function() {
    $('#t_PageBody').removeClass('js-regionIsMaximized');
    if ($('#wwvFlowForm').hasClass('js-regionIsMaximized')) {
        $('#wwvFlowForm').removeClass('js-regionIsMaximized');
    } else {
        $('#wwvFlowForm').addClass('js-regionIsMaximized');
    }
});
```

No need for a static ID anymore...

**Comment by pettinger** [comment]
Just as an Idea: Wouldn't it be better to grab the Tooltip Text from a hidden Column/Item instead? In that case i could format the content of the Tooltip. AFAIK there is not HTML formatting allowed in the "title" property-

**Comment by Dani3lSun** [comment]
Ok this is another thing, which have nothing to do with this issue...
but you can use html in an attribute but standard browser behavior doesn´t display it as actual html, but escaped...
The tooltip plugin can do it, the only thing you have to do is to set "Content with HTML" option to true...
<img width="409" alt="bildschirmfoto 2016-08-26 um 11 21 13" src="https://cloud.githubusercontent.com/assets/698942/18000757/dfab241e-6b7f-11e6-8d59-ad014f700eb2.png">
