### ISSUE TITLE
Tip does not work with ITEM set Display Only

### ISSUE THREAD

**Issue by rvnobre** [Dani3lSun/apex-plugin-apextooltip#5]
### Expected behavior
On a dialog i have a field with Display Only qnd tip does not fire, either hover or click.
### Actual behavior
It only work when Item set to Text Field

**Comment by Dani3lSun** [comment]
That's because it's not an input field anymore and the ID of the html element doesn't exist...
You have to do it via an JQuery Selector, e.g.
#P1_YOUR_ITEM_DISPLAY

So it is the item name + "_DISPLAY"
